name: Pip Package

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-pipenv
          restore-keys: |
            ${{ runner.os }}-pip-pipenv

      - name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies using pipenv
        run: |
          cd $GITHUB_WORKSPACE
          python -m pipenv install --dev

      - name: Generate Documentation
        run: |
          cd $GITHUB_WORKSPACE
          cd ./PYTHON_TEMPLATE/doc && pipenv run make html

      - name: Build Package
        run: |
          cd $GITHUB_WORKSPACE
          pipenv run python -m build

      - name: Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PIP_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          pipenv run twine upload --repository pypi dist/*

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Tar Archive Artifact
          path: ./dist/*
